/* AUTO-GENERATED by tools/cffi/generate_cdef.py -- do not edit by hand.
 * Source: ScienceMode4_c_library @ 0cb120160c58c96dbb103c92041446f33dbe8f69
 * Layers: general, low-level (ll), mid-level (ml).
 * Regenerate: python tools/cffi/generate_cdef.py
 */

typedef enum {
    Smpt_Cmd_Ll_Init = ...,
    Smpt_Cmd_Ll_Init_Ack = ...,
    Smpt_Cmd_Ll_Channel_Config = ...,
    Smpt_Cmd_Ll_Channel_Config_Ack = ...,
    Smpt_Cmd_Ll_Stop = ...,
    Smpt_Cmd_Ll_Stop_Ack = ...,
    Smpt_Cmd_Ll_Emg_Switches = ...,
    Smpt_Cmd_Ll_Emg_Switches_Ack = ...,
    Smpt_Cmd_Ml_Init = ...,
    Smpt_Cmd_Ml_Init_Ack = ...,
    Smpt_Cmd_Ml_Update = ...,
    Smpt_Cmd_Ml_Update_Ack = ...,
    Smpt_Cmd_Ml_Stop = ...,
    Smpt_Cmd_Ml_Stop_Ack = ...,
    Smpt_Cmd_Ml_Get_Current_Data = ...,
    Smpt_Cmd_Ml_Get_Current_Data_Ack = ...,
    Smpt_Cmd_Get_Version_Main = ...,
    Smpt_Cmd_Get_Version_Main_Ack = ...,
    Smpt_Cmd_Get_Device_Id = ...,
    Smpt_Cmd_Get_Device_Id_Ack = ...,
    Smpt_Cmd_Get_Battery_Status = ...,
    Smpt_Cmd_Get_Battery_Status_Ack = ...,
    Smpt_Cmd_Set_Power = ...,
    Smpt_Cmd_Set_Power_Ack = ...,
    Smpt_Cmd_Reset = ...,
    Smpt_Cmd_Reset_Ack = ...,
    Smpt_Cmd_Get_Version_Stim = ...,
    Smpt_Cmd_Get_Version_Stim_Ack = ...,
    Smpt_Cmd_Get_Stim_Status = ...,
    Smpt_Cmd_Get_Stim_Status_Ack = ...,
    Smpt_Cmd_Get_Main_Status = ...,
    Smpt_Cmd_Get_Main_Status_Ack = ...,
    Smpt_Cmd_General_Error = ...,
    Smpt_Cmd_Unknown_Cmd = ...,
    Smpt_Cmd_Get_Extended_Version = ...,
    Smpt_Cmd_Get_Extended_Version_Ack = ...,
    Smpt_Cmd_Dl_Init = ...,
    Smpt_Cmd_Dl_Init_Ack = ...,
    Smpt_Cmd_Dl_Start = ...,
    Smpt_Cmd_Dl_Start_Ack = ...,
    Smpt_Cmd_Dl_Stop = ...,
    Smpt_Cmd_Dl_Stop_Ack = ...,
    Smpt_Cmd_Dl_Send_Live_Data = ...,
    Smpt_Cmd_Dl_Send_File = ...,
    Smpt_Cmd_Dl_Send_MMI = ...,
    Smpt_Cmd_Dl_Get = ...,
    Smpt_Cmd_Dl_Get_Ack = ...,
    Smpt_Cmd_Dl_Power_Module = ...,
    Smpt_Cmd_Dl_Power_Module_Ack = ...,
    Smpt_Cmd_Dl_Send_File_Ack = ...,
    Smpt_Cmd_Dl_Sys = ...,
    Smpt_Cmd_Dl_Sys_Ack = ...,
    Smpt_Cmd_Bl_Init = ...,
    Smpt_Cmd_Bl_Init_Ack = ...,
    Smpt_Cmd_Bl_Update_Init = ...,
    Smpt_Cmd_Bl_Update_Init_Ack = ...,
    Smpt_Cmd_Bl_Update_Block = ...,
    Smpt_Cmd_Bl_Update_Block_Ack = ...,
    Smpt_Cmd_Bl_Update_Stop = ...,
    Smpt_Cmd_Bl_Update_Stop_Ack = ...,
    Smpt_Cmd_Sl_Test_Memory_Card = ...,
    Smpt_Cmd_Sl_Test_Memory_Card_Ack = ...,
    Smpt_Cmd_Sl_Set_Debug = ...,
    Smpt_Cmd_Sl_Set_Debug_Ack = ...,
    Smpt_Cmd_Sl_Debug_Message = ...,
    Smpt_Cmd_Sl_Set_Fuel_Gauge = ...,
    Smpt_Cmd_Sl_Set_Fuel_Gauge_Ack = ...,
    Smpt_Cmd_Sl_Set_Bluetooth = ...,
    Smpt_Cmd_Sl_Set_Bluetooth_Ack = ...,
    Smpt_Cmd_Sl_Set_Device_Id = ...,
    Smpt_Cmd_Sl_Set_Device_Id_Ack = ...,
    Smpt_Cmd_Last_Item = ...
} Smpt_Cmd;
typedef enum {
    Smpt_Cmd_Numbers_Low_Level_Min = ...,
    Smpt_Cmd_Numbers_Low_Level_Max = ...,
    Smpt_Cmd_Numbers_Mid_Level_Min = ...,
    Smpt_Cmd_Numbers_Mid_Level_Max = ...,
    Smpt_Cmd_Numbers_General_Level_Min = ...,
    Smpt_Cmd_Numbers_General_Level_Max = ...,
    Smpt_Cmd_Numbers_Service_Level_Min = ...,
    Smpt_Cmd_Numbers_Service_Level_Max = ...,
    Smpt_Cmd_Numbers_DysCom_Level_Min = ...,
    Smpt_Cmd_Numbers_DysCom_Level_Max = ...,
    Smpt_Cmd_Numbers_Boot_Level_Min = ...,
    Smpt_Cmd_Numbers_Boot_Level_Max = ...
} Smpt_Cmd_Numbers_Min_Max;
typedef enum {
    Smpt_Result_Successful = ...,
    Smpt_Result_Transfer_Error = ...,
    Smpt_Result_Parameter_Error = ...,
    Smpt_Result_Protocol_Error = ...,
    Smpt_Result_Uc_Stim_Timeout_Error = ...,
    Smpt_Result_Emg_Timeout_Error = ...,
    Smpt_Result_Emg_Register_Error = ...,
    Smpt_Result_Not_Initialized_Error = ...,
    Smpt_Result_Hv_Error = ...,
    Smpt_Result_Demux_Timeout_Error = ...,
    Smpt_Result_Electrode_Error = ...,
    Smpt_Result_Invalid_Cmd_Error = ...,
    Smpt_Result_Demux_Parameter_Error = ...,
    Smpt_Result_Demux_Not_Initialized_Error = ...,
    Smpt_Result_Demux_Transfer_Error = ...,
    Smpt_Result_Demux_Unknown_Ack_Error = ...,
    Smpt_Result_Pulse_Timeout_Error = ...,
    Smpt_Result_Fuel_Gauge_Error = ...,
    Smpt_Result_Live_Signal_Error = ...,
    Smpt_Result_File_Transmission_Timeout = ...,
    Smpt_Result_File_Not_Found = ...,
    Smpt_Result_Busy = ...,
    Smpt_Result_File_Error = ...,
    Smpt_Result_Flash_Erase_Error = ...,
    Smpt_Result_Flash_Write_Error = ...,
    Smpt_Result_Unknown_Controller_Error = ...,
    Smpt_Result_Firmware_Too_Large_Error = ...,
    Smpt_Result_Fuel_Gauge_Not_Programmed = ...,
    Smpt_Result_Pulse_Low_Current_Error = ...,
    Smpt_Result_Last_Item = ...
} Smpt_Result;
typedef enum {
    Smpt_Length_Number_Of_Channels = ...,
    Smpt_Length_Number_Of_Acks = ...,
    Smpt_Length_Serial_Port_Chars = ...,
    Smpt_Length_Points = ...,
    Smpt_Length_Header_Size = ...,
    Smpt_Length_Max_Packet_Size = ...,
    Smpt_Length_Max_Packet_Size_No_Emg = ...,
    Smpt_Length_Packet_Input_Buffer_Rows = ...,
    Smpt_Length_Debug_Messages = ...,
    Smpt_Length_Min_Packet_Size = ...,
    Smpt_Length_Device_Id = ...,
    Smpt_Length_Power_Modules = ...,
    Smpt_Length_Packet_Output_Buffer = ...,
    Smpt_Length_File_Name = ...
} Smpt_Length;
typedef enum {
    Smpt_Packet_Number_Modulo = ...
} Smpt_Constants_Diverse;
typedef enum {
    Smpt_Limit_Header_Size = ...,
    Smpt_Limit_Max_Packet_Size = ...,
    Smpt_Limit_Max_Packet_Size_No_Emg = ...,
    Smpt_Limit_Min_Packet_Size = ...
} Smpt_Limit;
typedef enum {
    Smpt_Channel_Red = ...,
    Smpt_Channel_Blue = ...,
    Smpt_Channel_Black = ...,
    Smpt_Channel_White = ...,
    Smpt_Channel_Undefined = ...
} Smpt_Channel;
typedef enum {
    Smpt_Connector_Yellow = ...,
    Smpt_Connector_Green = ...,
    Smpt_Connector_Undefined = ...
} Smpt_Connector;
typedef enum {
    Smpt_High_Voltage_Default = ...,
    Smpt_High_Voltage_Off = ...,
    Smpt_High_Voltage_30V = ...,
    Smpt_High_Voltage_60V = ...,
    Smpt_High_Voltage_90V = ...,
    Smpt_High_Voltage_120V = ...,
    Smpt_High_Voltage_150V = ...,
    Smpt_High_Voltage_Last_Item = ...
} Smpt_High_Voltage;
typedef enum {
    Smpt_Measurement_None = ...,
    Smpt_Measurement_Stim_Current = ...,
    Smpt_Measurement_Stim_Voltage = ...,
    Smpt_Measurement_High_Voltage = ...,
    Smpt_Measurement_Last_Item = ...
} Smpt_Measurement;
typedef enum {
    Smpt_Main_Status_Uninitialized = ...,
    Smpt_Main_Status_Dm_Initialized = ...,
    Smpt_Main_Status_Dm_Running = ...,
    Smpt_Main_Status_Last_Item = ...
} Smpt_Main_Status;
typedef enum {
    Smpt_Stim_Status_Uninitialized = ...,
    Smpt_Stim_Status_Ll_Initialized = ...,
    Smpt_Stim_Status_Ml_Initialized = ...,
    Smpt_Stim_Status_Ml_Running = ...,
    Smpt_Stim_Status_Last_Item = ...
} Smpt_Stim_Status;
typedef struct {
    uint16_t time;
    float current;
    uint8_t interpolation_mode;
    ...;
} Smpt_point;
typedef struct {
    uint8_t packet_number;
    uint16_t command_number;
    Smpt_Result result;
    ...;
} Smpt_ack;
typedef struct {
    uint8_t packet_number;
    uint16_t command_number;
    ...;
} Smpt_cmd;
typedef struct {
    uint32_t acks_length;
    uint32_t acks_current_index;
    Smpt_ack acks[...];
    uint32_t requests_current_index;
    uint32_t requests_expected_index;
    uint32_t number_of_expected;
    Smpt_cmd requests[...];
    uint32_t new_ack_available;
    ...;
} Smpt_cmd_list;
typedef struct {
    uint8_t *buffer;
    uint8_t *buffer_state;
    uint32_t write_row_length_count;
    uint32_t write_row_count;
    uint32_t read_row_count;
    bool ignore_next_byte;
    uint32_t number_of_rows;
    uint32_t row_length;
    ...;
} Packet_input_buffer;
typedef struct { ...; } Smpt_device;
typedef struct {
    uint8_t major;
    uint8_t minor;
    uint8_t revision;
    ...;
} Smpt_version;
typedef struct {
    Smpt_version fw_version;
    Smpt_version smpt_version;
    ...;
} Smpt_uc_version;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    Smpt_uc_version uc_version;
    ...;
} Smpt_get_version_ack;
typedef enum {
    Smpt_Fw_Hash_Type_Uninitialized = ...,
    Smpt_Fw_Hash_Type_Git = ...,
    Smpt_Fw_Hash_Type_Elf_MD5 = ...,
    Smpt_Fw_Hash_Type_Elf_Sha256 = ...,
    Smpt_Fw_Hash_Type_Last_Item = ...
} Smpt_Fw_Hash_Type;
typedef enum {
    Smpt_Fw_Hash_State_Not_Valid = ...,
    Smpt_Fw_Hash_State_Valid = ...,
    Smpt_Fw_Hash_State_Last_Item = ...
} Smpt_Fw_Hash_State_Type;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    Smpt_uc_version uc_version;
    uint32_t fw_hash;
    Smpt_Fw_Hash_Type fw_hash_type;
    Smpt_Fw_Hash_State_Type fw_hash_state;
    ...;
} Smpt_get_extended_version_ack;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    char device_id[...];
    ...;
} Smpt_get_device_id_ack;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    uint8_t battery_level;
    uint16_t battery_voltage;
    ...;
} Smpt_get_battery_status_ack;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    Smpt_Stim_Status stim_status;
    Smpt_High_Voltage high_voltage_level;
    ...;
} Smpt_get_stim_status_ack;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    Smpt_Main_Status main_status;
    ...;
} Smpt_get_main_status_ack;
typedef enum {
    Smpt_Library_Version_Major = ...,
    Smpt_Library_Version_Minor = ...,
    Smpt_Library_Version_Revision = ...
} Smpt_General;
typedef enum {
    Smpt_Power_Uc_Stim = ...,
    Smpt_Power_Bluetooth = ...,
    Smpt_Power_Emg = ...,
    Smpt_Power_Memory_Card = ...,
    Smpt_Power_Demux = ...
} Smpt_Power;
typedef struct {
    uint8_t packet_number;
    bool modules[...];
    ...;
} Smpt_set_power;
typedef enum {
    Smpt_Ll_Interpolation_Jump = ...,
    Smpt_Ll_Interpolation_Linear = ...,
    Smpt_Ll_Interpolation_Last_Item = ...
} Smpt_Ll_Interpolation_Mode;
typedef struct {
    Smpt_Measurement measurement_type;
    Smpt_High_Voltage high_voltage_level;
    uint8_t packet_number;
    ...;
} Smpt_ll_init;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    ...;
} Smpt_ll_init_ack;
typedef Smpt_point Smpt_ll_point;
typedef struct {
    bool enable_stimulation;
    Smpt_Channel channel;
    Smpt_Connector connector;
    uint8_t number_of_points;
    Smpt_ll_point points[...];
    uint8_t packet_number;
    ...;
} Smpt_ll_channel_config;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    Smpt_Channel channel;
    Smpt_Connector connector;
    Smpt_Measurement measurement_type;
    uint16_t measurement_sampling_time_us;
    uint16_t measurement[...];
    ...;
} Smpt_ll_channel_config_ack;
typedef Smpt_ack Smpt_ll_ack;
typedef struct {
    bool stop_all_channels_on_error;
    uint8_t packet_number;
    ...;
} Smpt_ml_init;
typedef Smpt_ack Smpt_ml_ack;
typedef Smpt_point Smpt_ml_point;
typedef struct {
    uint8_t ramp;
    float period;
    bool double_period_accuracy;
    uint8_t number_of_points;
    Smpt_ml_point points[...];
    ...;
} Smpt_ml_channel_config;
typedef struct {
    bool enable_channel[...];
    Smpt_ml_channel_config channel_config[...];
    uint8_t packet_number;
    ...;
} Smpt_ml_update;
typedef enum {
    Smpt_Ml_Data_Stimulation = ...,
    Smpt_Ml_Data_Stimulation_Eight_Channels = ...,
    Smpt_Ml_Data_Channels = ...
} Smpt_Ml_Data;
typedef struct {
    uint8_t packet_number;
    Smpt_Ml_Data data_selection;
    ...;
} Smpt_ml_get_current_data;
typedef enum {
    Smpt_Ml_Stimulation_Stopped = ...,
    Smpt_Ml_Stimulation_Running = ...,
    Smpt_Ml_Stimulation_Last_Item = ...
} Smpt_Ml_Stimulation_State;
typedef enum {
    Smpt_Ml_Channel_State_Ok = ...,
    Smpt_Ml_Channel_State_Electrode_Error = ...,
    Smpt_Ml_Channel_State_Timeout_Error = ...,
    Smpt_Ml_Channel_State_Low_Current_Error = ...,
    Smpt_Ml_Channel_State_Last_Item = ...
} Smpt_Ml_Channel_State;
typedef struct {
    bool is_valid;
    bool electrode_error[...];
    Smpt_Ml_Stimulation_State stimulation_state;
    ...;
} Smpt_ml_stimulation_data;
typedef struct {
    bool is_valid;
    Smpt_Ml_Channel_State channel_state[...];
    Smpt_Ml_Stimulation_State stimulation_state[...];
    ...;
} Smpt_ml_stimulation_channels_data;
typedef struct {
    uint8_t packet_number;
    Smpt_Result result;
    Smpt_Ml_Data data_selection;
    Smpt_ml_stimulation_data stimulation_data;
    Smpt_ml_stimulation_channels_data channel_data;
    ...;
} Smpt_ml_get_current_data_ack;

void smpt_clear_ack(Smpt_ack * const ack);
void smpt_clear_get_battery_status_ack(Smpt_get_battery_status_ack * const get_battery_status_ack);
void smpt_clear_get_device_id_ack(Smpt_get_device_id_ack * const get_device_id_ack);
void smpt_clear_get_version_ack(Smpt_get_version_ack * const get_version_ack);
void smpt_clear_get_extended_version_ack(Smpt_get_extended_version_ack * const get_extended_version_ack);
void smpt_clear_get_stim_status_ack(Smpt_get_stim_status_ack * const get_stim_status_ack);
void smpt_clear_get_main_status_ack(Smpt_get_main_status_ack * const get_main_status_ack);
void smpt_clear_device(Smpt_device * const device);
bool smpt_is_general(Smpt_Cmd cmd);
bool smpt_is_low_level(Smpt_Cmd cmd);
bool smpt_is_mid_level(Smpt_Cmd cmd);
bool smpt_is_dyscom_level(Smpt_Cmd cmd);
bool smpt_is_boot_level(Smpt_Cmd cmd);
bool smpt_is_service_level(Smpt_Cmd cmd);
void smpt_packet_number_generator_reset(Smpt_device * const device);
uint8_t smpt_packet_number_generator_next(Smpt_device * const device);
bool smpt_open_serial_port(Smpt_device * const device, const char * const device_name);
bool smpt_close_serial_port(Smpt_device * const device);
bool smpt_check_serial_port(const char * const device_name);
bool smpt_new_packet_received(Smpt_device * const device);
void smpt_last_ack(Smpt_device * const device, Smpt_ack * const ack);
bool smpt_send_get_version_main(Smpt_device * const device, uint8_t packet_number);
bool smpt_send_get_version_stim(Smpt_device * const device, uint8_t packet_number);
bool smpt_send_get_extended_version(Smpt_device * const device, uint8_t packet_number);
bool smpt_send_get_device_id(Smpt_device * const device, uint8_t packet_number);
bool smpt_send_get_battery_status(Smpt_device * const device, uint8_t packet_number);
bool smpt_send_reset(Smpt_device * const device, uint8_t packet_number);
bool smpt_send_get_stim_status(Smpt_device * const device, uint8_t packet_number);
bool smpt_send_get_main_status(Smpt_device * const device, uint8_t packet_number);
bool smpt_get_get_version_main_ack(Smpt_device * const device, Smpt_get_version_ack * const get_version_ack);
bool smpt_get_get_version_stim_ack(Smpt_device * const device, Smpt_get_version_ack * const get_version_ack);
bool smpt_get_get_extended_version_ack(Smpt_device * const device, Smpt_get_extended_version_ack * const get_extended_version_ack);
bool smpt_get_get_device_id_ack(Smpt_device * const device, Smpt_get_device_id_ack * const get_device_id_ack);
bool smpt_get_get_battery_status_ack(Smpt_device * const device, Smpt_get_battery_status_ack * const get_battery_status_ack);
bool smpt_get_get_stim_status_ack(Smpt_device * const device, Smpt_get_stim_status_ack * const get_stim_status_ack);
bool smpt_get_get_main_status_ack(Smpt_device * const device, Smpt_get_main_status_ack * const get_main_status_ack);
Smpt_version smpt_library_version(void);
bool smpt_send_cmd(Smpt_device * const device, uint8_t packet_number, Smpt_Cmd cmd_type);
void smpt_clear_set_power(Smpt_set_power * const set_power);
bool smpt_send_set_power(Smpt_device * const device, const Smpt_set_power * const set_power);
void smpt_clear_ll_init(Smpt_ll_init * const ll_init);
void smpt_clear_ll_init_ack(Smpt_ll_init_ack * const ll_init_ack);
void smpt_clear_ll_channel_config(Smpt_ll_channel_config * const ll_channel_config);
void smpt_clear_ll_channel_config_ack(Smpt_ll_channel_config_ack * const ll_channel_config_ack);
void smpt_clear_ll_ack(Smpt_ll_ack * const ll_ack);
void smpt_clear_ll_point(Smpt_ll_point * const ll_point);
bool smpt_send_ll_init(Smpt_device * const device, const Smpt_ll_init * const ll_init);
bool smpt_send_ll_channel_config(Smpt_device * const device, const Smpt_ll_channel_config * const ll_channel_config);
bool smpt_send_ll_stop(Smpt_device * const device, uint8_t packet_number);
bool smpt_get_ll_init_ack(const Smpt_device * const device, Smpt_ll_init_ack * const ll_init_ack);
bool smpt_get_ll_channel_config_ack(const Smpt_device * const device, Smpt_ll_channel_config_ack * const ll_channel_config_ack);
void smpt_clear_ml_init(Smpt_ml_init * const ml_init);
void smpt_clear_ml_update(Smpt_ml_update * const ml_update);
void smpt_clear_ml_get_current_data(Smpt_ml_get_current_data * const ml_get_current_data);
void smpt_clear_ml_get_current_data_ack(Smpt_ml_get_current_data_ack * const ml_get_current_data_ack);
void smpt_clear_ml_ack(Smpt_ml_ack * const ml_ack);
bool smpt_send_ml_init(Smpt_device * const device, const Smpt_ml_init * const ml_init);
bool smpt_send_ml_update(Smpt_device * const device, const Smpt_ml_update * const ml_update);
bool smpt_send_ml_get_current_data(Smpt_device * const device, const Smpt_ml_get_current_data * const ml_get_current_data);
bool smpt_send_ml_stop(Smpt_device * const device, uint8_t packet_number);
bool smpt_get_ml_get_current_data_ack(Smpt_device * const device, Smpt_ml_get_current_data_ack * const ml_get_current_data_ack);
